# Generated by Django 4.2.10 on 2025-09-14 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_add_organization_management"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationmembership",
            name="invited_by",
        ),
        migrations.RemoveField(
            model_name="organizationmembership",
            name="joined_at",
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="OrganizationInvitation",
        ),
    ]
