# Generated by Django 4.2.10 on 2025-08-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_blockchain_block_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='blockchain_block_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='blockchain_tx_hash',
        ),
        migrations.RemoveField(
            model_name='address',
            name='ipfs_hash',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_stored_on_blockchain',
        ),
    ]
