# Generated by Django 4.2.10 on 2025-08-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_remove_blockchain_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='suburb',
        ),
        migrations.AddField(
            model_name='address',
            name='blockchain_block_number',
            field=models.BigIntegerField(blank=True, help_text='Block number where address was stored', null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ipfs_hash',
            field=models.CharField(blank=True, help_text='IPFS hash for additional data', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='is_stored_on_blockchain',
            field=models.BooleanField(default=False, help_text='Whether address is stored on blockchain'),
        ),
    ]
