# Generated by Django 4.2.10 on 2025-09-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0006_encrypt_address_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this address was last synced to blockchain",
                null=True,
            ),
        ),
    ]
